/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      fontFamily: {
        display: ['BricolageGrotesque-ExtraBold'],
        'display-bold': ['BricolageGrotesque-Bold'],
        'display-semibold': ['BricolageGrotesque-SemiBold'],
        body: ['Manrope-Regular'],
        'body-medium': ['Manrope-Medium'],
        'body-semibold': ['Manrope-SemiBold'],
        'body-bold': ['Manrope-Bold'],
        'body-extrabold': ['Manrope-ExtraBold'],
      },
      colors: {
        background: '#0B0914',
        foreground: '#F7F5FF',
        card: '#191824',
        sheet: '#0B0914',
        gold: '#F5B544',
        'gold-ink': '#1A1206',
        'gold-bg': '#241C0B',
        'gold-line': '#5A4718',
        'purple-soft': '#B8ADFF',
        'purple-line': '#4A3F7A',
        'purple-tint': '#2A2140',
        border: '#363342',
        'border-muted': '#4A4659',
        primary: '#A58AFF',
        'primary-dark': '#211B43',
        'primary-border': '#8A6BFF',
        'nav-background': '#100E1B',
        'text-dark': '#10152F',
        'text-navy': '#111B42',
        'text-body': '#E7E4EF',
        muted: '#9A97A9',
        'muted-light': '#687087',
        coral: '#FF786F',
        avatar: '#77717C',
        'icon-dark': '#080711',
        'google-border': '#E7E9EC',
        'google-border-mid': '#C6CFD8',
        'google-border-blue': '#5D86AA',
        shadow: '#7D8794',
        'glow-green': '#34D399',
        'glow-emerald': '#10B981',
        'glow-violet': '#8B5CF6',
      },
    },
  },
  plugins: [],
};
